#colors:
#  # Default colors
#  primary:
#    background: '0x000000'
#    foreground: '0xd3d3d3'
#
#  # Normal colors
#  normal:
#    black:   '0x201e24'
#    red:     '0x2d2b30'
#    green:   '0x3f3d40'
#    yellow:  '0x413c3e'
#    blue:    '0x423e41'
#    magenta: '0x4e4a4b'
#    cyan:    '0x6e6765'
#    white:   '0x837e81'
#
#  # Bright colors
#  bright:
#    black:   '0x837c78'
#    red:     '0x89827d'
#    green:   '0xa7a099'
#    yellow:  '0xc2bec1'
#    blue:    '0xc3bcb2'
#    magenta: '0xcbc5ba'
#    cyan:    '0xe3ddd2'
#    white:   '0xefe8dc'




colors:
  # Default colors
  primary:
    background: '0x000000'
    foreground: '0xd3d3d3'

  # Normal colors
  normal:
    black:   '0x101010'
    red:     '0x7c7c7c'
    green:   '0x8e8e8e'
    yellow:  '0xa0a0a0'
    blue:    '0x686868'
    magenta: '0x747474'
    cyan:    '0x868686'
    white:   '0xb9b9b9'

  # Bright colors
  bright:
    black:   '0x525252'
    red:     '0x7c7c7c'
    green:   '0x8e8e8e'
    yellow:  '0xa0a0a0'
    blue:    '0x686868'
    magenta: '0x747474'
    cyan:    '0x868686'
    white:   '0xf7f7f7'




# Font configuration (changes require restart)
font:
  normal:
    family: Iosevka Nerd Font

  bold:
    family: Iosevka Nerd Font

  italic:
    family: Iosevka Nerd Font

  offset:
    x: 0
    y: 0

  glyph_offset:
    x: 0
    y: 0

  use_thin_strokes: true

draw_bold_text_with_bright_colors: false

custom_cursor_colors: true
















font:
  size: 8
